all: MyMainClass.class
	@echo \##############################################
	@echo
	@java MyMainClass
	@echo
	@echo \##############################################
MyMainClass.class: MyMainClass.java
	@javac MyMainClass.java
clean:
	@rm *.class